### ISSUE TITLE
Error al ver el display de una pagina basica

### ISSUE THREAD

**Issue by molteni-pedro** [diegosebastiangutierrez/utn8.ac.cr#1]
Al intentar ver el display del content type "Página básica" se muestra un error
https://utn.gruposmint.com/admin/structure/types/manage/page/display

`El sitio web encontró un error inesperado. Vuelva a intentarlo más tarde.

Symfony\Component\Routing\Exception\RouteNotFoundException: Route "entity.migration_group.list" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 206 of core/lib/Drupal/Core/Routing/RouteProvider.php).The website encountered an unexpected error. Please try again later.
TypeError: Cannot access offset of type string on string in Drupal\field_slideshow\Plugin\Field\FieldFormatter\FieldSlideshow->viewElements() (line 466 of modules/contrib/field_slideshow/src/Plugin/Field/FieldFormatter/FieldSlideshow.php).`

**Comment by molteni-pedro** [comment]
El mismo error se presenta al querer editar un display del tipo de contenido "carrera"

https://utn.gruposmint.com/admin/structure/types/manage/carrera/display

**Comment by diegosebastiangutierrez** [comment]
A mi me tira esto:

The website encountered an unexpected error. Please try again later.
TypeError: array_filter(): Argument #1 ($array) must be of type array, string given in array_filter() (line 186 of modules/contrib/field_slideshow/src/Plugin/Field/FieldFormatter/FieldSlideshow.php).

**Comment by molteni-pedro** [comment]
si se desístala el modulo FieldSlideshow, funciona el display correctamente

**Comment by diegosebastiangutierrez** [comment]
Y no se rompe nada de todo lo que usa ese tipo de campo?
